[package]
name = "udpt-rs"
version = "3.0.0-alpha"
authors = ["Naim A. <naim@abda.nl>"]
description = "High performance torrent tracker"
edition = "2018"

[profile.release]
lto = "fat"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
bincode = "1.2"
actix-web = "0.7"
actix-net = "0.2"
binascii = "0.1"
toml = "0.5"
clap = "2.33"
log = "0.4"
fern = "0.6"
num_cpus = "1.13"
serde_json = "1.0"
bzip2 = "0.3"
futures = "0.1"
lazy_static = "1.4"
