[package]
name = "udpt-rs"
version = "3.0.0-alpha"
authors = ["Naim A. <naim@abda.nl>"]
description = "High performance torrent tracker"
edition = "2018"

[profile.release]
lto = "fat"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
bincode = "1.2"
warp = {version = "0.2", default-features = false}
tokio = {version = "0.2", features = ["macros", "net", "rt-threaded", "fs", "sync", "blocking", "signal"]}
binascii = "0.1"
toml = "0.5"
clap = "2.33"
log = "0.4"
fern = "0.6"
serde_json = "1.0"
