mode = "dynamic"
db_path = "database.json.bz2"
log_level = "trace"

[udp]
announce_interval = 120         # Two minutes
bind_address = "0.0.0.0:1212"

[http]
bind_address = "127.0.0.1:1212"

[http.access_tokens]
someone = "MyAccessToken"
